/*
 * frmMain.java
 *
 * Created on November 21, 2008, 9:56 AM
 */

/*
Copyright (c) 2008, George Blouin Jr. (skyhigh@solaris7.com)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are
permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of
conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list
of conditions and the following disclaimer in the documentation and/or other materials
provided with the distribution.
    * Neither the name of George Blouin Jr nor the names of contributors may be
used to endorse or promote products derived from this software without specific prior
written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

package bvcalc;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import java.util.prefs.*;

/**
 *
 * @author  justin
 */
public class frmMain2 extends javax.swing.JFrame {
    public Force leftForce = new Force();
    public Force rightForce = new Force();
    private Preferences Prefs;

    /** Creates new form frmMain */
    public frmMain2() {
        initComponents();
        Load();
        Prefs = Preferences.userNodeForPackage(this.getClass());
    }

    public void Load(){
        tblForce.setModel( leftForce );
        tblForce2.setModel ( rightForce );

        txtForceName.setText(leftForce.ForceName);
        txtForceName1.setText(rightForce.ForceName);
    }

    public void RefreshDisplay() {
        leftForce.OpForSize = rightForce.Units.size();
        rightForce.OpForSize = leftForce.Units.size();
        leftForce.RefreshBV();
        rightForce.RefreshBV();

        lblUnitCountVal.setText(""+leftForce.Units.size());
        lblUnitsCountVal1.setText(""+rightForce.Units.size());

        lblTotalTonnageVal.setText(String.format( "%1$,.2f", leftForce.TotalTonnage));
        lblTotalTonnageVal1.setText(String.format( "%1$,.2f", rightForce.TotalTonnage));

        lblTotalBVVal.setText(String.format("%1$,.0f", leftForce.TotalBaseBV));
        lblTotalBVVal1.setText(String.format("%1$,.0f", rightForce.TotalBaseBV));

        lblC3BVVal.setText(String.format("%1$,.0f", leftForce.TotalC3BV));
        lblC3BVVal1.setText(String.format("%1$,.0f", rightForce.TotalC3BV));

        lblTotalModifierBVVal.setText(String.format("%1$,.0f", leftForce.TotalModifierBV));
        lblTotalModifierBVVal1.setText(String.format("%1$,.0f", rightForce.TotalModifierBV));

        lblForceBVVal.setText(String.format( "%1$,.0f", leftForce.TotalForceBV));
        lblForceBVVal1.setText(String.format( "%1$,.0f", rightForce.TotalForceBV));

        lblForceMultVal.setText(String.format( "%1$,.2f", CommonTools.GetForceSizeMultiplier(leftForce.Units.size(), rightForce.Units.size())));
        lblForceMultiplierAdjustedVal.setText(String.format("%1$,.0f", leftForce.TotalForceBVAdjusted));
        lblForceMultiplierAdjustedVal1.setText(String.format("%1$,.0f", rightForce.TotalForceBVAdjusted));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mnuPopUp = new javax.swing.JPopupMenu();
        mnuAdd = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenuItem();
        mnuDelete = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblForce = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAddUnit = new javax.swing.JButton();
        btnEditUnit = new javax.swing.JButton();
        btnRemoveUnit = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lblForceName = new javax.swing.JLabel();
        txtForceName = new javax.swing.JTextField();
        btnLoadFromFile = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnAddUnit1 = new javax.swing.JButton();
        btnEditUnit1 = new javax.swing.JButton();
        btnRemoveUnit1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lblForceName1 = new javax.swing.JLabel();
        txtForceName1 = new javax.swing.JTextField();
        btnLoadFromFile1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblForce2 = new javax.swing.JTable();
        lblTotalBaseBV = new javax.swing.JPanel();
        lblUnitCount = new javax.swing.JLabel();
        lblTotalTonnage = new javax.swing.JLabel();
        lblTotalBV = new javax.swing.JLabel();
        lblC3BV = new javax.swing.JLabel();
        lblTotalModifierBV = new javax.swing.JLabel();
        lblForceBV = new javax.swing.JLabel();
        lblForceMultiplierAdjusted = new javax.swing.JLabel();
        lblUnitCountVal = new javax.swing.JLabel();
        lblTotalTonnageVal = new javax.swing.JLabel();
        lblTotalBVVal = new javax.swing.JLabel();
        lblC3BVVal = new javax.swing.JLabel();
        lblTotalModifierBVVal = new javax.swing.JLabel();
        lblForceBVVal = new javax.swing.JLabel();
        lblForceMultiplierAdjustedVal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblUnitCount1 = new javax.swing.JLabel();
        lblTotalTonnage1 = new javax.swing.JLabel();
        lblTotalBV1 = new javax.swing.JLabel();
        lblC3BV1 = new javax.swing.JLabel();
        lblTotalModifierBV1 = new javax.swing.JLabel();
        lblForceBV1 = new javax.swing.JLabel();
        lblForceMultiplierAdjusted1 = new javax.swing.JLabel();
        lblUnitsCountVal1 = new javax.swing.JLabel();
        lblTotalTonnageVal1 = new javax.swing.JLabel();
        lblTotalBVVal1 = new javax.swing.JLabel();
        lblC3BVVal1 = new javax.swing.JLabel();
        lblTotalModifierBVVal1 = new javax.swing.JLabel();
        lblForceBVVal1 = new javax.swing.JLabel();
        lblForceMultiplierAdjustedVal1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel1 = new javax.swing.JLabel();
        lblForceMultVal = new javax.swing.JLabel();
        lblForceMult = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuSave = new javax.swing.JMenuItem();
        mnuLoad = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JSeparator();
        mnuPrint = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mnuExit = new javax.swing.JMenuItem();
        mnuAbout = new javax.swing.JMenu();
        mnuAboutCalc = new javax.swing.JMenuItem();

        mnuAdd.setText("Add Unit");
        mnuAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAddActionPerformed(evt);
            }
        });
        mnuPopUp.add(mnuAdd);

        mnuEdit.setText("Edit Unit");
        mnuEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditActionPerformed(evt);
            }
        });
        mnuPopUp.add(mnuEdit);

        mnuDelete.setText("Delete Unit");
        mnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDeleteActionPerformed(evt);
            }
        });
        mnuPopUp.add(mnuDelete);

        mnuPopUp.getAccessibleContext().setAccessibleParent(jScrollPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CBT Force Balancer");
        setMinimumSize(new java.awt.Dimension(550, 570));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(750, 250));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 250));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fileDropped(evt);
            }
        });

        tblForce.setAutoCreateRowSorter(true);
        tblForce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblForce.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblForce.setShowVerticalLines(false);
        tblForce.getTableHeader().setReorderingAllowed(false);
        tblForce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblForceMouseClicked(evt);
            }
        });
        tblForce.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblForceKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblForce);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel1.setMaximumSize(new java.awt.Dimension(101, 110));
        jPanel1.setMinimumSize(new java.awt.Dimension(101, 30));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnAddUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/add2.png"))); // NOI18N
        btnAddUnit.setToolTipText("Add Unit");
        btnAddUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUnitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(btnAddUnit, gridBagConstraints);

        btnEditUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/edit.png"))); // NOI18N
        btnEditUnit.setToolTipText("Edit Unit");
        btnEditUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUnitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnEditUnit, gridBagConstraints);

        btnRemoveUnit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/delete2.png"))); // NOI18N
        btnRemoveUnit.setToolTipText("Delete Unit");
        btnRemoveUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUnitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(btnRemoveUnit, gridBagConstraints);

        jSeparator4.setForeground(java.awt.SystemColor.control);
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jSeparator4, gridBagConstraints);

        lblForceName.setText("Force Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(lblForceName, gridBagConstraints);

        txtForceName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtForceName.setPreferredSize(new java.awt.Dimension(200, 20));
        txtForceName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtForceNameFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(txtForceName, gridBagConstraints);

        btnLoadFromFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/export1.png"))); // NOI18N
        btnLoadFromFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(btnLoadFromFile, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 1);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel4.setMinimumSize(new java.awt.Dimension(101, 30));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        btnAddUnit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/add2.png"))); // NOI18N
        btnAddUnit1.setToolTipText("Add Unit");
        btnAddUnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUnit1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(btnAddUnit1, gridBagConstraints);

        btnEditUnit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/edit.png"))); // NOI18N
        btnEditUnit1.setToolTipText("Edit Unit");
        btnEditUnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditUnit1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel4.add(btnEditUnit1, gridBagConstraints);

        btnRemoveUnit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/delete2.png"))); // NOI18N
        btnRemoveUnit1.setToolTipText("Delete Unit");
        btnRemoveUnit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUnit1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(btnRemoveUnit1, gridBagConstraints);

        jSeparator5.setForeground(new java.awt.Color(236, 233, 216));
        jSeparator5.setPreferredSize(new java.awt.Dimension(50, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jSeparator5, gridBagConstraints);

        lblForceName1.setText("Force Name: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel4.add(lblForceName1, gridBagConstraints);

        txtForceName1.setMinimumSize(new java.awt.Dimension(150, 20));
        txtForceName1.setPreferredSize(new java.awt.Dimension(200, 20));
        txtForceName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtForceName1FocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(txtForceName1, gridBagConstraints);

        btnLoadFromFile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bvcalc/export1.png"))); // NOI18N
        btnLoadFromFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadFromFile1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel4.add(btnLoadFromFile1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(jPanel4, gridBagConstraints);

        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(750, 250));
        jScrollPane2.setOpaque(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(750, 250));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fileDropped(evt);
            }
        });

        tblForce2.setAutoCreateRowSorter(true);
        tblForce2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblForce2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblForce2.setShowVerticalLines(false);
        tblForce2.getTableHeader().setReorderingAllowed(false);
        tblForce2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblForce2MouseClicked(evt);
            }
        });
        tblForce2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblForce2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblForce2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        lblTotalBaseBV.setLayout(new java.awt.GridBagLayout());

        lblUnitCount.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblUnitCount.setText("Units");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblUnitCount, gridBagConstraints);

        lblTotalTonnage.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalTonnage.setText("Tonnage");
        lblTotalTonnage.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblTotalTonnage, gridBagConstraints);

        lblTotalBV.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalBV.setText("Base BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblTotalBV, gridBagConstraints);

        lblC3BV.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblC3BV.setText("C3 BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblC3BV, gridBagConstraints);

        lblTotalModifierBV.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalModifierBV.setText("Mod BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblTotalModifierBV, gridBagConstraints);

        lblForceBV.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblForceBV.setText("Force BV");
        lblForceBV.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblForceBV, gridBagConstraints);

        lblForceMultiplierAdjusted.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblForceMultiplierAdjusted.setText("Multiplier Adj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        lblTotalBaseBV.add(lblForceMultiplierAdjusted, gridBagConstraints);

        lblUnitCountVal.setText("0");
        lblUnitCountVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblUnitCountVal, gridBagConstraints);

        lblTotalTonnageVal.setText("0");
        lblTotalTonnageVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblTotalTonnageVal, gridBagConstraints);

        lblTotalBVVal.setText("0");
        lblTotalBVVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblTotalBVVal, gridBagConstraints);

        lblC3BVVal.setText("0");
        lblC3BVVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblC3BVVal, gridBagConstraints);

        lblTotalModifierBVVal.setText("0");
        lblTotalModifierBVVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblTotalModifierBVVal, gridBagConstraints);

        lblForceBVVal.setText("0");
        lblForceBVVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblForceBVVal, gridBagConstraints);

        lblForceMultiplierAdjustedVal.setText("0");
        lblForceMultiplierAdjustedVal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        lblTotalBaseBV.add(lblForceMultiplierAdjustedVal, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(lblTotalBaseBV, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        lblUnitCount1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblUnitCount1.setText("Units");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblUnitCount1, gridBagConstraints);

        lblTotalTonnage1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalTonnage1.setText("Tonnage");
        lblTotalTonnage1.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblTotalTonnage1, gridBagConstraints);

        lblTotalBV1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalBV1.setText("Base BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblTotalBV1, gridBagConstraints);

        lblC3BV1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblC3BV1.setText("C3 BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblC3BV1, gridBagConstraints);

        lblTotalModifierBV1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblTotalModifierBV1.setText("Mod BV");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblTotalModifierBV1, gridBagConstraints);

        lblForceBV1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblForceBV1.setText("Force BV");
        lblForceBV1.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(lblForceBV1, gridBagConstraints);

        lblForceMultiplierAdjusted1.setFont(new java.awt.Font("Trebuchet MS", 0, 12));
        lblForceMultiplierAdjusted1.setText("Multiplier Adj");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel3.add(lblForceMultiplierAdjusted1, gridBagConstraints);

        lblUnitsCountVal1.setText("0");
        lblUnitsCountVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblUnitsCountVal1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblUnitsCountVal1, gridBagConstraints);

        lblTotalTonnageVal1.setText("0");
        lblTotalTonnageVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblTotalTonnageVal1, gridBagConstraints);

        lblTotalBVVal1.setText("0");
        lblTotalBVVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblTotalBVVal1, gridBagConstraints);

        lblC3BVVal1.setText("0");
        lblC3BVVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblC3BVVal1, gridBagConstraints);

        lblTotalModifierBVVal1.setText("0");
        lblTotalModifierBVVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblTotalModifierBVVal1, gridBagConstraints);

        lblForceBVVal1.setText("0");
        lblForceBVVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblForceBVVal1, gridBagConstraints);

        lblForceMultiplierAdjustedVal1.setText("0");
        lblForceMultiplierAdjustedVal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.ipady = 1;
        jPanel3.add(lblForceMultiplierAdjustedVal1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        getContentPane().add(jPanel3, gridBagConstraints);

        jSeparator1.setMaximumSize(new java.awt.Dimension(0, 2));
        jSeparator1.setMinimumSize(new java.awt.Dimension(0, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.ipady = 4;
        getContentPane().add(jSeparator1, gridBagConstraints);

        jSplitPane1.setBorder(null);

        jLabel1.setText("jLabel1");
        jSplitPane1.setLeftComponent(jLabel1);

        lblForceMultVal.setText("0");
        jSplitPane1.setRightComponent(lblForceMultVal);

        lblForceMult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblForceMult.setText("Force Multiplier");
        lblForceMult.setToolTipText("The modifier applied to the larger force");
        lblForceMult.setAlignmentX(0.5F);
        lblForceMult.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jSplitPane1.setLeftComponent(lblForceMult);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(jSplitPane1, gridBagConstraints);

        mnuFile.setText("File");

        mnuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuSave.setText("Save");
        mnuSave.setName("mnuSave"); // NOI18N
        mnuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaveActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSave);

        mnuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnuLoad.setText("Load");
        mnuLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoadActionPerformed(evt);
            }
        });
        mnuFile.add(mnuLoad);
        mnuFile.add(jSeparator3);

        mnuPrint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuPrint.setText("Print");
        mnuPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrintActionPerformed(evt);
            }
        });
        mnuFile.add(mnuPrint);
        mnuFile.add(jSeparator2);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        jMenuBar1.add(mnuFile);

        mnuAbout.setText("Help");

        mnuAboutCalc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        mnuAboutCalc.setText("About");
        mnuAboutCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutCalcActionPerformed(evt);
            }
        });
        mnuAbout.add(mnuAboutCalc);

        jMenuBar1.add(mnuAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnAddUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUnitActionPerformed
    dlgAddEdit Editor = new dlgAddEdit( this, true );
    Editor.setLocationRelativeTo( this );
    Editor.setVisible( true );
    if( Editor.GetResult() ) {
        leftForce.AddUnit(Editor.GetUnit());
        RefreshDisplay();
    }
}//GEN-LAST:event_btnAddUnitActionPerformed

private void btnEditUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUnitActionPerformed
    Unit u = (Unit) leftForce.Units.get( tblForce.getSelectedRow() );
    dlgAddEdit Editor = new dlgAddEdit( this, true, u );
    Editor.setTitle("Edit Unit");
    Editor.setLocationRelativeTo( this );
    Editor.setVisible( true );
    if( Editor.GetResult() ) {
        leftForce.AddUnit(Editor.GetUnit());
        RefreshDisplay();
    }
}//GEN-LAST:event_btnEditUnitActionPerformed

private void btnRemoveUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUnitActionPerformed
    leftForce.RemoveUnit((Unit) leftForce.Units.get(tblForce.getSelectedRow()));
    RefreshDisplay();
}//GEN-LAST:event_btnRemoveUnitActionPerformed

private void tblForceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblForceMouseClicked
    if (evt.getClickCount() >= 2) { btnEditUnitActionPerformed(null); }
    if (evt.getButton() == MouseEvent.BUTTON3) {
        mnuPopUp.setLocation(evt.getLocationOnScreen());
        mnuPopUp.setInvoker(evt.getComponent());
        mnuEdit.setEnabled(true);
        mnuDelete.setEnabled(true);
        mnuPopUp.setVisible(true);
    }
}//GEN-LAST:event_tblForceMouseClicked

private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        try {
            Prefs.exportNode(new FileOutputStream("preferences.xml"));
        } catch (IOException ex) {
            Logger.getLogger(frmMain2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BackingStoreException ex) {
            Logger.getLogger(frmMain2.class.getName()).log(Level.SEVERE, null, ex);
        }
    if ((leftForce.isDirty) || (rightForce.isDirty)) {
        switch (javax.swing.JOptionPane.showConfirmDialog(this, "Would you like to save your changes?")) {
            case javax.swing.JOptionPane.YES_OPTION:
                this.mnuSaveActionPerformed(evt);
            case javax.swing.JOptionPane.NO_OPTION:
                this.dispose();
        }
    } else {
        this.dispose();
    }
}//GEN-LAST:event_mnuExitActionPerformed

private void tblForce2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblForce2MouseClicked
    if (evt.getClickCount() >= 2) { btnEditUnit1ActionPerformed(null); }
    if (evt.getButton() == MouseEvent.BUTTON3) {
        mnuPopUp.setLocation(evt.getLocationOnScreen());
        mnuPopUp.setInvoker(evt.getComponent());
        mnuEdit.setEnabled(true);
        mnuDelete.setEnabled(true);
        mnuPopUp.setVisible(true);
    }
}//GEN-LAST:event_tblForce2MouseClicked

private void btnAddUnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUnit1ActionPerformed
    dlgAddEdit Editor = new dlgAddEdit( this, true );
    Editor.setLocationRelativeTo( this );
    Editor.setVisible( true );
    if( Editor.GetResult() ) {
        rightForce.AddUnit( Editor.GetUnit() );
        RefreshDisplay();
    }
}//GEN-LAST:event_btnAddUnit1ActionPerformed

private void btnEditUnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditUnit1ActionPerformed
    Unit u = (Unit) rightForce.Units.get( tblForce2.getSelectedRow() );
    dlgAddEdit Editor = new dlgAddEdit( this, true, u );
    Editor.setTitle("Edit Unit");
    Editor.setLocationRelativeTo( this );
    Editor.setVisible( true );
    if( Editor.GetResult() ) {
        rightForce.AddUnit( Editor.GetUnit() );
        RefreshDisplay();
    }
}//GEN-LAST:event_btnEditUnit1ActionPerformed

private void btnRemoveUnit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUnit1ActionPerformed
    rightForce.RemoveUnit((Unit) rightForce.Units.get(tblForce2.getSelectedRow()));
    RefreshDisplay();
}//GEN-LAST:event_btnRemoveUnit1ActionPerformed

private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
    if (evt.getButton() == MouseEvent.BUTTON3) {
        mnuPopUp.setLocation(evt.getLocationOnScreen());
        mnuPopUp.setInvoker(evt.getComponent());
        mnuEdit.setEnabled(false);
        mnuDelete.setEnabled(false);
        mnuPopUp.setVisible(true);
    } else {
        btnAddUnitActionPerformed(null);
    }
}//GEN-LAST:event_jScrollPane1MouseClicked

private void tblForceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblForceKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
        btnRemoveUnitActionPerformed(null);
    }
}//GEN-LAST:event_tblForceKeyPressed

private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
    if (evt.getButton() == MouseEvent.BUTTON3) {
        mnuPopUp.setLocation(evt.getLocationOnScreen());
        mnuPopUp.setInvoker(evt.getComponent());
        mnuEdit.setEnabled(false);
        mnuDelete.setEnabled(false);
        mnuPopUp.setVisible(true);
    } else {
       btnAddUnit1ActionPerformed(null);
    }
}//GEN-LAST:event_jScrollPane2MouseClicked

private void tblForce2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblForce2KeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
        btnRemoveUnit1ActionPerformed(null);
    }
}//GEN-LAST:event_tblForce2KeyPressed

private void mnuAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAddActionPerformed
    if (mnuPopUp.getInvoker().equals(tblForce)) {
        btnAddUnitActionPerformed(evt);
    } else if (mnuPopUp.getInvoker().equals(tblForce2)) {
        btnAddUnit1ActionPerformed(evt);
    } else if (mnuPopUp.getInvoker().equals(jScrollPane1)) {
        btnAddUnitActionPerformed(evt);
    } else if (mnuPopUp.getInvoker().equals(jScrollPane2)) {
        btnAddUnit1ActionPerformed(evt);
    }
}//GEN-LAST:event_mnuAddActionPerformed

private void mnuEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditActionPerformed
     if (mnuPopUp.getInvoker().equals(tblForce)) {
         btnEditUnitActionPerformed(evt);
    } else if (mnuPopUp.getInvoker().equals(tblForce2)) {
        btnEditUnit1ActionPerformed(evt);
    }
}//GEN-LAST:event_mnuEditActionPerformed

private void mnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDeleteActionPerformed
    if (mnuPopUp.getInvoker().equals(tblForce)) {
        btnRemoveUnitActionPerformed(evt);
    } else if (mnuPopUp.getInvoker().equals(tblForce2)) {
        btnRemoveUnit1ActionPerformed(evt);
    }
}//GEN-LAST:event_mnuDeleteActionPerformed

private void mnuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaveActionPerformed
    if ((!txtForceName.getText().isEmpty()) && (!txtForceName1.getText().isEmpty())) {
        try {
            String filename = (Prefs.get("LastOpenDirectory", "") + CommonTools.FormatFileName(txtForceName.getText() + "_vs_" + txtForceName1.getText() + ".xml"));
            XMLWriter write = new XMLWriter(this.leftForce, this.rightForce);
            write.WriteXML(filename);
            //write.SerializeForce(leftForce);
            //write.SerializeForce(rightForce);
            Prefs.put("LastOpenFile", filename);
            javax.swing.JOptionPane.showMessageDialog(this, "Forces saved to " + filename);
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter Force Names before saving.");
    }
}//GEN-LAST:event_mnuSaveActionPerformed

private void mnuAboutCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutCalcActionPerformed
    dlgAbout About = new dlgAbout();
    About.setTitle("About Battle Value Calculator");
    About.setLocationRelativeTo(this);
    About.setVisible(true);
}//GEN-LAST:event_mnuAboutCalcActionPerformed

private void txtForceNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForceNameFocusLost
    leftForce.ForceName = txtForceName.getText();
    leftForce.isDirty = true;
}//GEN-LAST:event_txtForceNameFocusLost

private void txtForceName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtForceName1FocusLost
    rightForce.ForceName = txtForceName1.getText();
    rightForce.isDirty = true;
}//GEN-LAST:event_txtForceName1FocusLost

private void mnuLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoadActionPerformed
    File tempFile = new File(Prefs.get("LastOpenDirectory", ""));
    JFileChooser fc = new JFileChooser();
    fc.addChoosableFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()){
                    return true;
                }

                if (f.getName().indexOf(".") > 0) {
                    String extension = "" + f.getName().substring(f.getName().indexOf("."));
                    if (extension.equals(".xml")){
                        return true;
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "*.xml";
            }
        });
     fc.setAcceptAllFileFilterUsed( false );
     fc.setCurrentDirectory(tempFile);
     int returnVal = fc.showDialog( this, "Load Force Listing" );
       if( returnVal != JFileChooser.APPROVE_OPTION ) { return; }
       File ForceFile = fc.getSelectedFile();
       String filename = "";
       try {
           filename = ForceFile.getCanonicalPath();
           Prefs.put("LastOpenDirectory", ForceFile.getCanonicalPath().replace(ForceFile.getName(), ""));
           Prefs.put("LastOpenFile", ForceFile.getName());
       } catch( Exception e ) {
           javax.swing.JOptionPane.showMessageDialog( this, "There was a problem opening the file:\n" + e.getMessage() );
           return;
       }

       XMLReader reader = new XMLReader();
       try {
           reader.ReadFile(this, filename);
       } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog( this, "Issue loading file:\n " + e.getMessage() );
           return;
       }

}//GEN-LAST:event_mnuLoadActionPerformed

private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    mnuExitActionPerformed(null);
}//GEN-LAST:event_formWindowClosing

private void mnuPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrintActionPerformed
   PrinterJob job = PrinterJob.getPrinterJob();
   PrintSheet p = new PrintSheet(this, 576, 756);
   Paper paper = new Paper();
   paper.setImageableArea(18, 18, 576, 756 );
   PageFormat page = new PageFormat();
   page.setPaper( paper );
   job.setPrintable( p, page );
   boolean DoPrint = job.printDialog();
   if( DoPrint ) {
       try {
           job.print();
       } catch( PrinterException e ) {
           System.err.println( e.getMessage() );
           System.out.println( e.getStackTrace() );
       }
  }
}//GEN-LAST:event_mnuPrintActionPerformed

private void fileDropped(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileDropped

}//GEN-LAST:event_fileDropped

private void btnLoadFromFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFileActionPerformed
    File tempFile = new File(Prefs.get("LastLoadDirectory", ""));
    JFileChooser fc = new JFileChooser();
    fc.addChoosableFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()){
                    return true;
                }

                if (f.getName().indexOf(".") > 0) {
                    String extension = "" + f.getName().substring(f.getName().indexOf("."));
                    if (extension.equals(".ssw")){
                        return true;
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "*.ssw";
            }
        });
     fc.setAcceptAllFileFilterUsed( false );
     fc.setCurrentDirectory(tempFile);
     int returnVal = fc.showDialog( this, "Load SSW File" );
       if( returnVal != JFileChooser.APPROVE_OPTION ) { return; }
       File ForceFile = fc.getSelectedFile();
       String filename = "";
       try {
           filename = ForceFile.getCanonicalPath();
           Prefs.put("LastLoadDirectory", ForceFile.getCanonicalPath().replace(ForceFile.getName(), ""));
       } catch( Exception e ) {
           javax.swing.JOptionPane.showMessageDialog( this, "There was a problem opening the file:\n" + e.getMessage() );
           return;
       }

       SSWReader reader = new SSWReader();
       try {
           reader.ReadFile(this, this.leftForce, filename);
       } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog( this, "Issue loading file:\n " + e.getMessage() );
           return;
       }
}//GEN-LAST:event_btnLoadFromFileActionPerformed

private void btnLoadFromFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFromFile1ActionPerformed
    File tempFile = new File(Prefs.get("LastLoadDirectory", ""));
    JFileChooser fc = new JFileChooser();
    fc.addChoosableFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                if (f.isDirectory()){
                    return true;
                }

                if (f.getName().indexOf(".") > 0) {
                    String extension = "" + f.getName().substring(f.getName().indexOf("."));
                    if (extension.equals(".ssw")){
                        return true;
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            }

            @Override
            public String getDescription() {
                return "*.ssw";
            }
        });
     fc.setAcceptAllFileFilterUsed( false );
     fc.setCurrentDirectory(tempFile);
     int returnVal = fc.showDialog( this, "Load SSW File" );
       if( returnVal != JFileChooser.APPROVE_OPTION ) { return; }
       File ForceFile = fc.getSelectedFile();
       String filename = "";
       try {
           filename = ForceFile.getCanonicalPath();
           Prefs.put("LastLoadDirectory", ForceFile.getCanonicalPath().replace(ForceFile.getName(), ""));
       } catch( Exception e ) {
           javax.swing.JOptionPane.showMessageDialog( this, "There was a problem opening the file:\n" + e.getMessage() );
           return;
       }

       SSWReader reader = new SSWReader();
       try {
           reader.ReadFile(this, this.rightForce, filename);
       } catch (Exception e) {
           javax.swing.JOptionPane.showMessageDialog( this, "Issue loading file:\n " + e.getMessage() );
           return;
       }
}//GEN-LAST:event_btnLoadFromFile1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUnit;
    private javax.swing.JButton btnAddUnit1;
    private javax.swing.JButton btnEditUnit;
    private javax.swing.JButton btnEditUnit1;
    private javax.swing.JButton btnLoadFromFile;
    private javax.swing.JButton btnLoadFromFile1;
    private javax.swing.JButton btnRemoveUnit;
    private javax.swing.JButton btnRemoveUnit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblC3BV;
    private javax.swing.JLabel lblC3BV1;
    private javax.swing.JLabel lblC3BVVal;
    private javax.swing.JLabel lblC3BVVal1;
    private javax.swing.JLabel lblForceBV;
    private javax.swing.JLabel lblForceBV1;
    private javax.swing.JLabel lblForceBVVal;
    private javax.swing.JLabel lblForceBVVal1;
    private javax.swing.JLabel lblForceMult;
    private javax.swing.JLabel lblForceMultVal;
    private javax.swing.JLabel lblForceMultiplierAdjusted;
    private javax.swing.JLabel lblForceMultiplierAdjusted1;
    private javax.swing.JLabel lblForceMultiplierAdjustedVal;
    private javax.swing.JLabel lblForceMultiplierAdjustedVal1;
    private javax.swing.JLabel lblForceName;
    private javax.swing.JLabel lblForceName1;
    private javax.swing.JLabel lblTotalBV;
    private javax.swing.JLabel lblTotalBV1;
    private javax.swing.JLabel lblTotalBVVal;
    private javax.swing.JLabel lblTotalBVVal1;
    private javax.swing.JPanel lblTotalBaseBV;
    private javax.swing.JLabel lblTotalModifierBV;
    private javax.swing.JLabel lblTotalModifierBV1;
    private javax.swing.JLabel lblTotalModifierBVVal;
    private javax.swing.JLabel lblTotalModifierBVVal1;
    private javax.swing.JLabel lblTotalTonnage;
    private javax.swing.JLabel lblTotalTonnage1;
    private javax.swing.JLabel lblTotalTonnageVal;
    private javax.swing.JLabel lblTotalTonnageVal1;
    private javax.swing.JLabel lblUnitCount;
    private javax.swing.JLabel lblUnitCount1;
    private javax.swing.JLabel lblUnitCountVal;
    private javax.swing.JLabel lblUnitsCountVal1;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenuItem mnuAboutCalc;
    private javax.swing.JMenuItem mnuAdd;
    private javax.swing.JMenuItem mnuDelete;
    private javax.swing.JMenuItem mnuEdit;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuLoad;
    private javax.swing.JPopupMenu mnuPopUp;
    private javax.swing.JMenuItem mnuPrint;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JTable tblForce;
    private javax.swing.JTable tblForce2;
    private javax.swing.JTextField txtForceName;
    private javax.swing.JTextField txtForceName1;
    // End of variables declaration//GEN-END:variables

}
